// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type NatDnatKey struct {
	_        structs.HostLayout
	HostIp   uint32
	HostPort uint16
	Proto    uint8
	Pad      uint8
}

type NatDnatVal struct {
	_          structs.HostLayout
	VmIp       uint32
	TapIfindex uint32
	VmPort     uint16
	VmMac      [6]uint8
}

type NatGlobalConfig struct {
	_                   structs.HostLayout
	HostIp              uint32
	UplinkIfindex       uint32
	GwIp                uint32
	GwMac               [6]uint8
	DefaultEgressAllow  uint8
	DefaultIngressAllow uint8
}

type NatNatEvent struct {
	_         structs.HostLayout
	OrigSaddr uint32
	OrigDaddr uint32
	NewSaddr  uint32
	NewDaddr  uint32
	VmIp      uint32
	OrigSport uint16
	OrigDport uint16
	NewSport  uint16
	NewDport  uint16
	Len       uint16
	Proto     uint8
	Dir       uint8
	Verdict   uint8
	Pad       [3]uint8
}

type NatNatStats struct {
	_       structs.HostLayout
	RxPkts  uint64
	RxBytes uint64
	TxPkts  uint64
	TxBytes uint64
	Drops   uint64
	Conns   uint64
}

type NatPolicyKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type NatPolicyVal struct {
	_       structs.HostLayout
	Verdict uint8
	Pad     uint8
	Port    uint16
}

type NatVmEntry struct {
	_          structs.HostLayout
	VmIp       uint32
	TapIfindex uint32
	VmMac      [6]uint8
	Pad        [2]uint8
}

// LoadNat returns the embedded CollectionSpec for Nat.
func LoadNat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Nat: %w", err)
	}

	return spec, err
}

// LoadNatObjects loads Nat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NatObjects
//	*NatPrograms
//	*NatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNatObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NatSpecs struct {
	NatProgramSpecs
	NatMapSpecs
	NatVariableSpecs
}

// NatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NatProgramSpecs struct {
	NatTap    *ebpf.ProgramSpec `ebpf:"nat_tap"`
	NatUplink *ebpf.ProgramSpec `ebpf:"nat_uplink"`
}

// NatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NatMapSpecs struct {
	DnatRules       *ebpf.MapSpec `ebpf:"dnat_rules"`
	EgressPolicy    *ebpf.MapSpec `ebpf:"egress_policy"`
	Events          *ebpf.MapSpec `ebpf:"events"`
	GlobalConfigMap *ebpf.MapSpec `ebpf:"global_config_map"`
	IngressPolicy   *ebpf.MapSpec `ebpf:"ingress_policy"`
	Stats           *ebpf.MapSpec `ebpf:"stats"`
	VmConfig        *ebpf.MapSpec `ebpf:"vm_config"`
}

// NatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NatVariableSpecs struct {
	UnusedNatEvent *ebpf.VariableSpec `ebpf:"_unused_nat_event"`
}

// NatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNatObjects or ebpf.CollectionSpec.LoadAndAssign.
type NatObjects struct {
	NatPrograms
	NatMaps
	NatVariables
}

func (o *NatObjects) Close() error {
	return _NatClose(
		&o.NatPrograms,
		&o.NatMaps,
	)
}

// NatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNatObjects or ebpf.CollectionSpec.LoadAndAssign.
type NatMaps struct {
	DnatRules       *ebpf.Map `ebpf:"dnat_rules"`
	EgressPolicy    *ebpf.Map `ebpf:"egress_policy"`
	Events          *ebpf.Map `ebpf:"events"`
	GlobalConfigMap *ebpf.Map `ebpf:"global_config_map"`
	IngressPolicy   *ebpf.Map `ebpf:"ingress_policy"`
	Stats           *ebpf.Map `ebpf:"stats"`
	VmConfig        *ebpf.Map `ebpf:"vm_config"`
}

func (m *NatMaps) Close() error {
	return _NatClose(
		m.DnatRules,
		m.EgressPolicy,
		m.Events,
		m.GlobalConfigMap,
		m.IngressPolicy,
		m.Stats,
		m.VmConfig,
	)
}

// NatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNatObjects or ebpf.CollectionSpec.LoadAndAssign.
type NatVariables struct {
	UnusedNatEvent *ebpf.Variable `ebpf:"_unused_nat_event"`
}

// NatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNatObjects or ebpf.CollectionSpec.LoadAndAssign.
type NatPrograms struct {
	NatTap    *ebpf.Program `ebpf:"nat_tap"`
	NatUplink *ebpf.Program `ebpf:"nat_uplink"`
}

func (p *NatPrograms) Close() error {
	return _NatClose(
		p.NatTap,
		p.NatUplink,
	)
}

func _NatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nat_bpfel.o
var _NatBytes []byte
