// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TapfilterConfig struct {
	_    structs.HostLayout
	Port uint16
	Drop uint8
	Pad  uint8
}

type TapfilterEvent struct {
	_       structs.HostLayout
	Saddr   uint32
	Daddr   uint32
	Sport   uint16
	Dport   uint16
	Len     uint16
	Ingress uint8
	Dropped uint8
	Proto   uint8
	Pad     [3]uint8
}

// LoadTapfilter returns the embedded CollectionSpec for Tapfilter.
func LoadTapfilter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TapfilterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Tapfilter: %w", err)
	}

	return spec, err
}

// LoadTapfilterObjects loads Tapfilter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TapfilterObjects
//	*TapfilterPrograms
//	*TapfilterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTapfilterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTapfilter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TapfilterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TapfilterSpecs struct {
	TapfilterProgramSpecs
	TapfilterMapSpecs
	TapfilterVariableSpecs
}

// TapfilterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TapfilterProgramSpecs struct {
	TapEgress  *ebpf.ProgramSpec `ebpf:"tap_egress"`
	TapIngress *ebpf.ProgramSpec `ebpf:"tap_ingress"`
}

// TapfilterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TapfilterMapSpecs struct {
	ConfigMap *ebpf.MapSpec `ebpf:"config_map"`
	Events    *ebpf.MapSpec `ebpf:"events"`
	Stats     *ebpf.MapSpec `ebpf:"stats"`
}

// TapfilterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TapfilterVariableSpecs struct {
	UnusedEvent *ebpf.VariableSpec `ebpf:"_unused_event"`
}

// TapfilterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTapfilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type TapfilterObjects struct {
	TapfilterPrograms
	TapfilterMaps
	TapfilterVariables
}

func (o *TapfilterObjects) Close() error {
	return _TapfilterClose(
		&o.TapfilterPrograms,
		&o.TapfilterMaps,
	)
}

// TapfilterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTapfilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type TapfilterMaps struct {
	ConfigMap *ebpf.Map `ebpf:"config_map"`
	Events    *ebpf.Map `ebpf:"events"`
	Stats     *ebpf.Map `ebpf:"stats"`
}

func (m *TapfilterMaps) Close() error {
	return _TapfilterClose(
		m.ConfigMap,
		m.Events,
		m.Stats,
	)
}

// TapfilterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTapfilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type TapfilterVariables struct {
	UnusedEvent *ebpf.Variable `ebpf:"_unused_event"`
}

// TapfilterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTapfilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type TapfilterPrograms struct {
	TapEgress  *ebpf.Program `ebpf:"tap_egress"`
	TapIngress *ebpf.Program `ebpf:"tap_ingress"`
}

func (p *TapfilterPrograms) Close() error {
	return _TapfilterClose(
		p.TapEgress,
		p.TapIngress,
	)
}

func _TapfilterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tapfilter_bpfel.o
var _TapfilterBytes []byte
