// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/aarani/craftling-go/internal/firecracker/models"
)

// PatchGuestPmemByIDReader is a Reader for the PatchGuestPmemByID structure.
type PatchGuestPmemByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchGuestPmemByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewPatchGuestPmemByIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPatchGuestPmemByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPatchGuestPmemByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPatchGuestPmemByIDNoContent creates a PatchGuestPmemByIDNoContent with default headers values
func NewPatchGuestPmemByIDNoContent() *PatchGuestPmemByIDNoContent {
	return &PatchGuestPmemByIDNoContent{}
}

/*
PatchGuestPmemByIDNoContent describes a response with status code 204, with default header values.

Pmem device updated
*/
type PatchGuestPmemByIDNoContent struct {
}

// IsSuccess returns true when this patch guest pmem by Id no content response has a 2xx status code
func (o *PatchGuestPmemByIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch guest pmem by Id no content response has a 3xx status code
func (o *PatchGuestPmemByIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch guest pmem by Id no content response has a 4xx status code
func (o *PatchGuestPmemByIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch guest pmem by Id no content response has a 5xx status code
func (o *PatchGuestPmemByIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this patch guest pmem by Id no content response a status code equal to that given
func (o *PatchGuestPmemByIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the patch guest pmem by Id no content response
func (o *PatchGuestPmemByIDNoContent) Code() int {
	return 204
}

func (o *PatchGuestPmemByIDNoContent) Error() string {
	return fmt.Sprintf("[PATCH /pmem/{id}][%d] patchGuestPmemByIdNoContent", 204)
}

func (o *PatchGuestPmemByIDNoContent) String() string {
	return fmt.Sprintf("[PATCH /pmem/{id}][%d] patchGuestPmemByIdNoContent", 204)
}

func (o *PatchGuestPmemByIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPatchGuestPmemByIDBadRequest creates a PatchGuestPmemByIDBadRequest with default headers values
func NewPatchGuestPmemByIDBadRequest() *PatchGuestPmemByIDBadRequest {
	return &PatchGuestPmemByIDBadRequest{}
}

/*
PatchGuestPmemByIDBadRequest describes a response with status code 400, with default header values.

Pmem device cannot be updated due to bad input
*/
type PatchGuestPmemByIDBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this patch guest pmem by Id bad request response has a 2xx status code
func (o *PatchGuestPmemByIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this patch guest pmem by Id bad request response has a 3xx status code
func (o *PatchGuestPmemByIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch guest pmem by Id bad request response has a 4xx status code
func (o *PatchGuestPmemByIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this patch guest pmem by Id bad request response has a 5xx status code
func (o *PatchGuestPmemByIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this patch guest pmem by Id bad request response a status code equal to that given
func (o *PatchGuestPmemByIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the patch guest pmem by Id bad request response
func (o *PatchGuestPmemByIDBadRequest) Code() int {
	return 400
}

func (o *PatchGuestPmemByIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /pmem/{id}][%d] patchGuestPmemByIdBadRequest %s", 400, payload)
}

func (o *PatchGuestPmemByIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /pmem/{id}][%d] patchGuestPmemByIdBadRequest %s", 400, payload)
}

func (o *PatchGuestPmemByIDBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PatchGuestPmemByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPatchGuestPmemByIDDefault creates a PatchGuestPmemByIDDefault with default headers values
func NewPatchGuestPmemByIDDefault(code int) *PatchGuestPmemByIDDefault {
	return &PatchGuestPmemByIDDefault{
		_statusCode: code,
	}
}

/*
PatchGuestPmemByIDDefault describes a response with status code -1, with default header values.

Internal server error.
*/
type PatchGuestPmemByIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this patch guest pmem by ID default response has a 2xx status code
func (o *PatchGuestPmemByIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this patch guest pmem by ID default response has a 3xx status code
func (o *PatchGuestPmemByIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this patch guest pmem by ID default response has a 4xx status code
func (o *PatchGuestPmemByIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this patch guest pmem by ID default response has a 5xx status code
func (o *PatchGuestPmemByIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this patch guest pmem by ID default response a status code equal to that given
func (o *PatchGuestPmemByIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the patch guest pmem by ID default response
func (o *PatchGuestPmemByIDDefault) Code() int {
	return o._statusCode
}

func (o *PatchGuestPmemByIDDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /pmem/{id}][%d] patchGuestPmemByID default %s", o._statusCode, payload)
}

func (o *PatchGuestPmemByIDDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /pmem/{id}][%d] patchGuestPmemByID default %s", o._statusCode, payload)
}

func (o *PatchGuestPmemByIDDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PatchGuestPmemByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
