// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/aarani/craftling-go/internal/firecracker/models"
)

// NewPatchGuestPmemByIDParams creates a new PatchGuestPmemByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchGuestPmemByIDParams() *PatchGuestPmemByIDParams {
	return &PatchGuestPmemByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchGuestPmemByIDParamsWithTimeout creates a new PatchGuestPmemByIDParams object
// with the ability to set a timeout on a request.
func NewPatchGuestPmemByIDParamsWithTimeout(timeout time.Duration) *PatchGuestPmemByIDParams {
	return &PatchGuestPmemByIDParams{
		timeout: timeout,
	}
}

// NewPatchGuestPmemByIDParamsWithContext creates a new PatchGuestPmemByIDParams object
// with the ability to set a context for a request.
func NewPatchGuestPmemByIDParamsWithContext(ctx context.Context) *PatchGuestPmemByIDParams {
	return &PatchGuestPmemByIDParams{
		Context: ctx,
	}
}

// NewPatchGuestPmemByIDParamsWithHTTPClient creates a new PatchGuestPmemByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchGuestPmemByIDParamsWithHTTPClient(client *http.Client) *PatchGuestPmemByIDParams {
	return &PatchGuestPmemByIDParams{
		HTTPClient: client,
	}
}

/*
PatchGuestPmemByIDParams contains all the parameters to send to the API endpoint

	for the patch guest pmem by ID operation.

	Typically these are written to a http.Request.
*/
type PatchGuestPmemByIDParams struct {

	/* Body.

	   Pmem rate limiter properties
	*/
	Body *models.PartialPmem

	/* ID.

	   The id of the guest pmem device
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch guest pmem by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchGuestPmemByIDParams) WithDefaults() *PatchGuestPmemByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch guest pmem by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchGuestPmemByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch guest pmem by ID params
func (o *PatchGuestPmemByIDParams) WithTimeout(timeout time.Duration) *PatchGuestPmemByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch guest pmem by ID params
func (o *PatchGuestPmemByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch guest pmem by ID params
func (o *PatchGuestPmemByIDParams) WithContext(ctx context.Context) *PatchGuestPmemByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch guest pmem by ID params
func (o *PatchGuestPmemByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch guest pmem by ID params
func (o *PatchGuestPmemByIDParams) WithHTTPClient(client *http.Client) *PatchGuestPmemByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch guest pmem by ID params
func (o *PatchGuestPmemByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch guest pmem by ID params
func (o *PatchGuestPmemByIDParams) WithBody(body *models.PartialPmem) *PatchGuestPmemByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch guest pmem by ID params
func (o *PatchGuestPmemByIDParams) SetBody(body *models.PartialPmem) {
	o.Body = body
}

// WithID adds the id to the patch guest pmem by ID params
func (o *PatchGuestPmemByIDParams) WithID(id string) *PatchGuestPmemByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch guest pmem by ID params
func (o *PatchGuestPmemByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchGuestPmemByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
