// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/aarani/craftling-go/internal/firecracker/models"
)

// StopBalloonHintingReader is a Reader for the StopBalloonHinting structure.
type StopBalloonHintingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopBalloonHintingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewStopBalloonHintingNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStopBalloonHintingBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewStopBalloonHintingDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewStopBalloonHintingNoContent creates a StopBalloonHintingNoContent with default headers values
func NewStopBalloonHintingNoContent() *StopBalloonHintingNoContent {
	return &StopBalloonHintingNoContent{}
}

/*
StopBalloonHintingNoContent describes a response with status code 204, with default header values.

Free page hinting run stopped.
*/
type StopBalloonHintingNoContent struct {
}

// IsSuccess returns true when this stop balloon hinting no content response has a 2xx status code
func (o *StopBalloonHintingNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this stop balloon hinting no content response has a 3xx status code
func (o *StopBalloonHintingNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stop balloon hinting no content response has a 4xx status code
func (o *StopBalloonHintingNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this stop balloon hinting no content response has a 5xx status code
func (o *StopBalloonHintingNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this stop balloon hinting no content response a status code equal to that given
func (o *StopBalloonHintingNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the stop balloon hinting no content response
func (o *StopBalloonHintingNoContent) Code() int {
	return 204
}

func (o *StopBalloonHintingNoContent) Error() string {
	return fmt.Sprintf("[PATCH /balloon/hinting/stop][%d] stopBalloonHintingNoContent", 204)
}

func (o *StopBalloonHintingNoContent) String() string {
	return fmt.Sprintf("[PATCH /balloon/hinting/stop][%d] stopBalloonHintingNoContent", 204)
}

func (o *StopBalloonHintingNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStopBalloonHintingBadRequest creates a StopBalloonHintingBadRequest with default headers values
func NewStopBalloonHintingBadRequest() *StopBalloonHintingBadRequest {
	return &StopBalloonHintingBadRequest{}
}

/*
StopBalloonHintingBadRequest describes a response with status code 400, with default header values.

The balloon free hinting was not enabled when the device was configured.
*/
type StopBalloonHintingBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this stop balloon hinting bad request response has a 2xx status code
func (o *StopBalloonHintingBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this stop balloon hinting bad request response has a 3xx status code
func (o *StopBalloonHintingBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stop balloon hinting bad request response has a 4xx status code
func (o *StopBalloonHintingBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this stop balloon hinting bad request response has a 5xx status code
func (o *StopBalloonHintingBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this stop balloon hinting bad request response a status code equal to that given
func (o *StopBalloonHintingBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the stop balloon hinting bad request response
func (o *StopBalloonHintingBadRequest) Code() int {
	return 400
}

func (o *StopBalloonHintingBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /balloon/hinting/stop][%d] stopBalloonHintingBadRequest %s", 400, payload)
}

func (o *StopBalloonHintingBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /balloon/hinting/stop][%d] stopBalloonHintingBadRequest %s", 400, payload)
}

func (o *StopBalloonHintingBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *StopBalloonHintingBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewStopBalloonHintingDefault creates a StopBalloonHintingDefault with default headers values
func NewStopBalloonHintingDefault(code int) *StopBalloonHintingDefault {
	return &StopBalloonHintingDefault{
		_statusCode: code,
	}
}

/*
StopBalloonHintingDefault describes a response with status code -1, with default header values.

Internal Server Error
*/
type StopBalloonHintingDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this stop balloon hinting default response has a 2xx status code
func (o *StopBalloonHintingDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this stop balloon hinting default response has a 3xx status code
func (o *StopBalloonHintingDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this stop balloon hinting default response has a 4xx status code
func (o *StopBalloonHintingDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this stop balloon hinting default response has a 5xx status code
func (o *StopBalloonHintingDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this stop balloon hinting default response a status code equal to that given
func (o *StopBalloonHintingDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the stop balloon hinting default response
func (o *StopBalloonHintingDefault) Code() int {
	return o._statusCode
}

func (o *StopBalloonHintingDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /balloon/hinting/stop][%d] stopBalloonHinting default %s", o._statusCode, payload)
}

func (o *StopBalloonHintingDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /balloon/hinting/stop][%d] stopBalloonHinting default %s", o._statusCode, payload)
}

func (o *StopBalloonHintingDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *StopBalloonHintingDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
